CREATE TABLE IF NOT EXISTS Authors(
	Id SERIAL PRIMARY KEY,
	Name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Books(
 	Id SERIAL PRIMARY KEY,
	Name VARCHAR(255),
	Author_Id INT,
	Quantity INT,
	FOREIGN KEY (Author_Id) REFERENCES Authors(Id)
);

CREATE TABLE IF NOT EXISTS Borrowers(
	Id SERIAL PRIMARY KEY,
	Name VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS Loans(
	Id SERIAL PRIMARY KEY,
	Borrower_Id INT,
	Book_Id INT,
	issued_books INT,
	Book_status VARCHAR(255),
	Date_Borrowed TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	Date_Returned TIMESTAMP,
	FOREIGN KEY (Borrower_Id) REFERENCES Borrowers(Id),
	FOREIGN KEY (Book_Id) REFERENCES Books(Id)
);
CREATE TABLE IF NOT EXISTS Loans_cart(
	Id SERIAL PRIMARY KEY,
	Book_Name VARCHAR(255),
	Quantity INT
);
CREATE TABLE IF NOT EXISTS Roles(
	Id SERIAL PRIMARY KEY,
	Role VARCHAR(120) NOT NULL
);
CREATE TABLE IF NOT EXISTS Users(
	Id SERIAL PRIMARY KEY,
	Username VARCHAR(255) UNIQUE NOT NULL,
	Email VARCHAR(120) UNIQUE NOT NULL,
	Hashed_Password TEXT NOT NULL,
	Role_id INT,
	FOREIGN KEY (Role_id) REFERENCES Roles(Id) 
)
