CREATE TABLE IF NOT EXISTS Authors(
	Id SERIAL PRIMARY KEY,
	Name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Books(
 	Id SERIAL PRIMARY KEY,
	Name VARCHAR(255),
	Author_Id INT,
	FOREIGN KEY (Author_Id) REFERENCES Authors(Id)
);

CREATE TABLE IF NOT EXISTS Borrowers(
	Id SERIAL PRIMARY KEY,
	Name VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS Loans(
	Id SERIAL PRIMARY KEY,
	Borrower_Id INT,
	Book_Id INT,
	Book_status VARCHAR(255),
	Date_Borrowed TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	Date_Returned TIMESTAMP,
	FOREIGN KEY (Borrower_Id) REFERENCES Borrowers(Id),
	FOREIGN KEY (Book_Id) REFERENCES Books(Id)
);